language: python
python:
    - 2.7
env:
    - TOXENV=py27-django16
before_install:
    - npm install --global bower
install:
    - pip install --requirement requirements.txt
    - pip install --editable .
script:
    - make test-tox
