version: '2.1'
services:
  curious:
    build: .
    volumes:
      - caches:/root/.cache
      - .:${CURIOUS_HOME:-/usr/src/curious}
      - bower_components:${CURIOUS_HOME:-/usr/src/curious}/curious/static/curious/lib
    tty:
      true
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}

volumes:
  caches:
  bower_components:
